// app/layout.js
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "../context/UserContext"; // ✅ import provider

export const metadata = {
  title: "CFO Craft Sales Dashboard",
  description: "Generated by CFO Craft Advisory Services Pvt. Ltd.",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* ✅ Wrap everything inside the UserProvider */}
        <UserProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#1f2937",
                color: "#fff",
                border: "1px solid #374151",
                borderRadius: "8px",
              },
              success: {
                iconTheme: {
                  primary: "#22c55e",
                  secondary: "#1f2937",
                },
              },
              error: {
                iconTheme: {
                  primary: "#ef4444",
                  secondary: "#1f2937",
                },
              },
            }}
          />
        </UserProvider>
      </body>
    </html>
  );
}
